### ISSUE TITLE
White/Black list not working/appearing on PiHole v5+ behind Nginx reverse proxy

### ISSUE THREAD

**Issue by serendrewpity** [badsgahhl/pihole-browser-extension#35]
Just reporting it here in the hopes of it being fixed
I am running an older version of chrome 
I have no desire to upgrade Chrome for privacy reasons
Which not so ironically is why I have PiHole.
So if it is a user error on my part then I'll live with it until I figure out what I am doing wrong.
If it is a currently unsupported use case then I'll live with it until it is supported (or not)
If all else fails I'll use the hostname or IP address of the PiHole [there's two] which, at the time of this writing I haven't tried yet.
What I am trying to say here is that I am not upgrading chrome.

**Comment by serendrewpity** [comment]
Damn, it.
I am running the latest version of Chrome!
It's currently at version 87.0.4280.66 (Official Build) (64-bit) on Windows 10
Chrome automatically upgraded itself after temporarily disabling PiHole 
This was even after I thought I disabled the Google Chrome updater service.

So it appears the extension is still not working with the latest version of chrome.
It is also not working with the hostname/IPAddress used in the extension settings
The piholes also have password disabled which appears to be a requirement for API use
But the extension works with out the API and will obviously disable PiHole for the 10s default.
Both PiHole DNS servers are above ver 5.

I'm going to downgrade chrome now.

**Comment by badsgahhl** [comment]
Just from my point of view, its an issue at the nginx configuration site.

If disabling works and the extension shows the status your settings are correct.
The only thing that the "List Feature" does differently to the disable thing, is that it also sends data via a POST Request.
Normally everything on the PiHole Api can be accessed by the URL directly. (e.G. http://ip/admin/api.php?disable=10)

But the listing feature calls a url (http://ip/admin/api.php?list=black&add=example.com) + in the POST Body it send a comment.
This could be one potential thing.

The things you could do now:

- Install Firefox and checkout if the extension works there
- Open the Popup, Right-Click into the window, and press "Inspect". There you go into the console and network tab. Then press the button to list a domain. Make screenshots of the console and network tab and post it into the issue here.


Little bit offtopic: Why are you using chrome then, and not a privacy friendly version of it like chromium, brave etc. The security issues you could get by using an older browser version is by far more critical than any data Google can steal from you.

**Comment by serendrewpity** [comment]
http://ip/admin/api.php?list=black&add=example.com, works. I get a 'success' for example.com without any POST Body.

RE: Chrome. My thinking on browsers and privacy in general is that it will always be a cat and mouse game. You have to keep chasing security updates to stay ahead of or at least keep up with the malicious actors or services out there. This simply is not efficient. A browser may be completely about privacy today and a tomorrow completely abandon that philosophy or have it revealed that they never honored it to begin with. I'm speaking directly about Brave Browser here. Browser, Operating Systems and Apps (mobiles, web & containerized) are evolving very fast. So naturally the tactics used by advertisers and trackers are potentially evolving as fast also. We don't know what we don't know. Should I really trust that {fill in the blank} is really more interested in my security and privacy than I am? ... And the threat is not just them. Our government steals our info all the time. [doesn't matter which government since they all spy on each other, ask Angela Merkle about the US government] Each iteration of an application, platform or operating system just furthers the interwoven nature of technology into our lives. Security is and will always be an issue of the highest priority. A part of security is how much can you find out about me from googling me. The security issues I'm making myself vulnerable to by not upgrading is a concern. I cannot get around that. But my privacy is becoming increasingly equal to the security concerns. Also, in most cases, I would have to do something that would make me a target of a malicious actor that could take advantage of my security vulnerabilities. It doesn't HAVE TO be a targeted attack but those are the ones I can guard against by taking my security into my own hands and not trusting it to a browser that disables extensions that I find useful 

I've talked too long, I could talk longer but the essence is that an older version of my Browser allows me to employ more efficient means of controlling my security while not passing off the responsibility to someone else ...and... always balancing it with my convenience and ease of access to data and services that I enjoy.

**Comment by badsgahhl** [comment]
I'll close this here. This is not reproducible on a fresh install of pihole and nginx as reverse proxy even on seperated systems. Probably caused by a miss configuration.
