### ISSUE TITLE
Adding 2. pi.hole instance does not allow to edit URL

### ISSUE THREAD

**Issue by Jpp909** [badsgahhl/pihole-browser-extension#48]
**Describe the bug**
I have a Docker instance running a pi.hole. I now added am instance running on a real Pi. When I try to add this as second instance in the browser extension by pressing (+) the URL is already populated with "http:/pi.hole/admin". In my case this is wrong as the it used by the (offline) Docker instance. Instead I must use either the IPv4 address or "pi-hole".
Here is the bug: There is no way to edit this URL field.

**To Reproduce**
as described above

**Expected behavior**
URL field for second entry should be editable, but the field is locked.

**Screenshots**
![Browser Extension Setup](https://user-images.githubusercontent.com/59258491/119261742-04566400-bbd9-11eb-8d05-9d781a2dfcf2.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64, latest version 21H1 Build 19043.985
 - Browser: Firefox, latest version 88.0.1 x64
 
Thanks for your attention to this (minor) problem and BIG THANKS for the extension.
Jpp909

**Comment by badsgahhl** [comment]
Hello 👋🏽,

thanks for reporting the bug. 

Actually this bug is not really reproducible for me. The "default" URL the UI is showing there is just a placeholder but doesn't do anything. The field to enter the IP or domain should never be "locked". At least i cannot find anything in the code that would do that.
Would it be possible to create a GIF or a short video trying to click into the field and entering an IP.

Best wishes
